/***************************************************************************//**
 * @file
 * @brief Core application logic.
 *******************************************************************************
 * # License
 * <b>Copyright 2022 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * SPDX-License-Identifier: Zlib
 *
 * The licensor of this software is Silicon Laboratories Inc.
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 ******************************************************************************/
#include "app_assert.h"
#include "app_log.h"
#include "sl_bluetooth.h"
#include "sl_main_init.h"
#include "sl_sleeptimer.h"
#include "gatt_db.h"

// Onboard inertial sensor: the BRD2606A carries an InvenSense ICM-40627
// 6-axis IMU on EUSART1 SPI with a board enable line (SL_BOARD_SENSOR_IMU,
// GPIO PC09). The Silicon Labs IMU fusion service (`sl_imu`) drives the
// ICM-40627 driver and produces filtered acceleration, gyro, and an
// orientation (Euler) estimate. We convert that orientation to a unit
// quaternion so the over-the-air manufacturer payload matches the format
// previously broadcast by the (retired) external MPU6050 bolt-on, keeping
// the host-side parser unchanged.
#include "sl_board_control.h"
#include "sl_imu.h"

// Onboard push buttons (BRD2606A): BTN0 (PB04) halts the firmware into a
// low-power standby; BTN1 (PB05) restarts it from the default boot state.
// RESET keeps its default hardware behaviour.
#include "sl_simple_button.h"
#include "sl_simple_button_instances.h"

#include <math.h>
#include <stdbool.h>
#include <string.h>

// CS reflector POC: the same connectable advertising set carries the CTE
// service for the AoA locator AND the RAS service (auto-contributed by
// `cs_ras_server`) for a CS initiator. When any peer connects we spin up a
// reflector instance for that connection; the CS handshake will simply
// never start if the peer is the AoA locator, and the reflector instance
// goes away on disconnect.
#include "cs_antenna.h"
#include "cs_reflector.h"
#include "cs_reflector_config.h"
#include "cs_sync_antenna.h"

// Default CTE advertising interval (SL_GATT_SERVICE_CTE_SILABS_ADV_INTERVAL)
// used when restoring the tone stream after a CS session ends.
#include "sl_gatt_service_cte_silabs_config.h"

// ---------------------------------------------------------------------------
// Optional per-tag pairing/bonding hardening (Layer 1 of the CS auth scheme).
// ---------------------------------------------------------------------------
// DEFAULT OFF. When CS_TAG_REQUIRE_BOND == 0 the tag behaves exactly as before
// (stack-default Security Manager, JustWorks, no bonding requested) so the
// working CS/AoA/IMU pipeline is untouched.
//
// When enabled (-DCS_TAG_REQUIRE_BOND=1) the tag offers Secure-Connections-
// only, bondable, debug-keys-rejected pairing. On this NoInputNoOutput board
// the over-the-air association is necessarily JustWorks: there is no
// display/keyboard, and a static factory OOB confirm is invalid for LE Secure
// Connections because the confirm value is f4(PK, PK, r, 0) -- bound to the
// per-pairing ECDH public key (verified against SDK 2025.12.3 sl_bt_sm_set_oob,
// whose random/confirm are OUT params generated by the stack). The defensible
// per-tag identity guarantee therefore comes from Layer 2 (host-side IRK pin);
// this layer only makes the link SC-only, bonded and encrypted, and is meant to
// be enrolled at the bench together with the matching initiator-side change.
#ifndef CS_TAG_REQUIRE_BOND
#define CS_TAG_REQUIRE_BOND 0
#endif

// The advertising set handle allocated from Bluetooth stack (connectable:
// AoA CTE + CS/RAS).
static uint8_t advertising_set_handle = 0xff;

// Dedicated non-connectable advertising set carrying the IMU manufacturer
// payload. It is never preempted by connection events so the inertial
// stream keeps broadcasting while a CS initiator / AoA locator is connected.
static uint8_t imu_set_handle = 0xff;

// Number of active connections.
static uint8_t connection_count = 0;

// Reflector defaults mirror the standalone CS reflector example.
static cs_reflector_config_t cs_reflector_config = {
  .max_tx_power_dbm = CS_REFLECTOR_MAX_TX_POWER_DBM,
  .cs_sync_antenna  = CS_REFLECTOR_CS_SYNC_ANTENNA
};

// ---------------------------------------------------------------------------
// AoA <-> CS mode switching, driven by connection state
// ---------------------------------------------------------------------------
// The CS initiator firmware is gated so it ONLY opens a connection to this tag
// when CS ranging is actually wanted (in AoA mode it stays disconnected). That
// makes "a connection is open" a true, race-free "CS mode active" signal here:
//
//   * Connected (CS mode):  pause the 20 ms Silabs CTE tone stream so the CS
//     reflector procedures get the radio, and push the IMU broadcaster up to
//     10 Hz now that CTE is no longer hogging airtime.
//   * Disconnected (AoA mode): restore the 20 ms CTE stream so the AoA locator
//     re-acquires, and return the IMU broadcaster to its AoA-mode adv cadence
//     (IMU_RATE_AOA_HZ); the host decimates the IMU stream as needed.
//
// CS "speed" itself is driven entirely by the initiator's procedure timing;
// the tag's only lever is freeing the radio (CTE off), which is exactly what
// lets the reflector keep up at the initiator's maximum cadence.
//
// `adv_cte_interval` and `adv_cte_start()` are non-static symbols provided by
// the gatt_service_cte_adv component (sl_gatt_service_cte_silabs.c). They are
// declared here so the app can drive them without pulling the component's
// internal header.
extern uint16_t adv_cte_interval;        // CTE adv interval, units of 0.625 ms
extern sl_status_t adv_cte_start(void);  // (re)start CTE adv with current params

#define CTE_ADV_INTERVAL_ACTIVE  ((uint16_t)SL_GATT_SERVICE_CTE_SILABS_ADV_INTERVAL) // 20 ms
#define CTE_ADV_INTERVAL_PAUSED  ((uint16_t)0xFFFFU)  // ~40.96 s => effectively off

// IMU broadcast rates for the two modes (Hz). These set the on-air advertising
// cadence of the dedicated IMU set; the payload itself is refreshed at the
// faster fusion rate (IMU_ADV_UPDATE_RATE_HZ) and only when a new fused sample
// is ready, so every aired packet is fresh and the sequence number advances
// exactly once per sample (see app_process_action / update_imu_advertising_packet).
#define IMU_RATE_AOA_HZ                     10U  // AoA mode: fast IMU; host decimates
#define IMU_RATE_CS_HZ                      10U  // CS mode: CTE paused, room to run

// Pause the CTE tone stream (CS session starting).
static void cte_pause(void)
{
  adv_cte_interval = CTE_ADV_INTERVAL_PAUSED;
  (void)adv_cte_start();
}

// Restore the 20 ms CTE tone stream (CS session ended).
static void cte_resume(void)
{
  adv_cte_interval = CTE_ADV_INTERVAL_ACTIVE;
  (void)adv_cte_start();
}

// ---------------------------------------------------------------------------
// IMU advertising
// ---------------------------------------------------------------------------

// Rate at which we refresh the IMU advertising payload. The fusion service
// is configured to sample at the same rate; sl_imu_is_data_ready() gates the
// actual read so we never block.
#define IMU_ADV_UPDATE_RATE_HZ              50U

// AD structure and payload definitions (identical to the MPU6050 tag so the
// host parser is unchanged).
#define AD_TYPE_FLAGS                       0x01U
#define AD_TYPE_MANUFACTURER_SPECIFIC_DATA  0xFFU
#define AD_FLAG_LE_GENERAL_DISCOVERABLE     0x02U
#define AD_FLAG_BR_EDR_NOT_SUPPORTED        0x04U

// Bluetooth SIG company identifier for Silicon Labs (little-endian in payload).
#define SILABS_COMPANY_ID                   0x02FFU

// Custom payload metadata for host-side parser.
#define IMU_PAYLOAD_MAGIC                   0x494DU // 'IM'
#define IMU_PAYLOAD_VERSION                 1U
// Length of the raw IMU payload shared by the advertisement (after company id)
// and the GATT notification: magic(2)+ver(1)+seq(1)+accel(6)+gyro(6)+quat(8).
#define IMU_PAYLOAD_LEN                     24U
#define IMU_STATUS_SAMPLE_VALID             0x01U
#define IMU_STATUS_IMU_INIT_OK              0x02U
#define IMU_STATUS_IMU_READ_OK              0x08U

typedef struct {
  int16_t accel_x_mg;
  int16_t accel_y_mg;
  int16_t accel_z_mg;
  int16_t gyro_x_dps;
  int16_t gyro_y_dps;
  int16_t gyro_z_dps;
  int16_t quat_x_x10000;
  int16_t quat_y_x10000;
  int16_t quat_z_x10000;
  int16_t quat_w_x10000;
  uint8_t status;
} imu_sample_t;

static bool bluetooth_ready = false;
static bool imu_ready = false;

// Button-driven power control (see sl_button_on_change / app_process_action).
// The handler runs in GPIO interrupt context, so it only sets a request flag;
// the actual work is done from the super loop.
static volatile bool halt_requested = false;    // BTN0: enter standby
static volatile bool resume_requested = false;  // BTN1: restart
static bool standby = false;                    // true while halted in standby
static uint8_t imu_sequence = 0;
static uint32_t imu_last_update_tick = 0;
static uint32_t imu_update_period_ticks = 1;
static uint32_t imu_timer_freq_hz = 32768U;

// CS-piggyback transport state. While a peer is connected, a standalone
// advertising set is starved to ~2-3 Hz, so we stream IMU samples over the
// connection via GATT notifications instead. active_connection holds the
// current peer handle (0xFF = none) and imu_notify_enabled tracks whether the
// peer has subscribed to the IMU Data characteristic (CCCD = notify).
static uint8_t active_connection = 0xFFU;
static bool imu_notify_enabled = false;

// Last good IMU output. Quaternion defaults to identity so adv packets are
// valid before the first fused sample arrives.
static int16_t imu_last_accel_mg[3] = { 0, 0, 0 };
static int16_t imu_last_gyro_dps[3] = { 0, 0, 0 };
static int16_t imu_last_quat_x10000[4] = { 0, 0, 0, 10000 }; // x, y, z, w

static inline void write_u16_le(uint8_t *buf, uint16_t value)
{
  buf[0] = (uint8_t)(value & 0xFFU);
  buf[1] = (uint8_t)((value >> 8U) & 0xFFU);
}

static int16_t sat_i16(int32_t value)
{
  if (value > 32767) {
    return 32767;
  }
  if (value < -32768) {
    return -32768;
  }
  return (int16_t)value;
}

// Convert a quaternion component in the range [-1, 1] to the int16 x10000
// over-the-air format used by the host parser.
static inline int16_t quat_to_x10000(float q)
{
  return sat_i16((int32_t)lrintf(q * 10000.0f));
}

// Convert the fusion service's Euler orientation (centidegrees, ZYX:
// roll about X, pitch about Y, yaw about Z) into a unit quaternion (x,y,z,w).
static void euler_centideg_to_quat(const int16_t ovec[3], int16_t quat_x10000[4])
{
  const float deg2rad = 0.017453292519943295f;
  float roll  = (float)ovec[0] * 0.01f * deg2rad;
  float pitch = (float)ovec[1] * 0.01f * deg2rad;
  float yaw   = (float)ovec[2] * 0.01f * deg2rad;

  float cr = cosf(roll * 0.5f);
  float sr = sinf(roll * 0.5f);
  float cp = cosf(pitch * 0.5f);
  float sp = sinf(pitch * 0.5f);
  float cy = cosf(yaw * 0.5f);
  float sy = sinf(yaw * 0.5f);

  float qw = cr * cp * cy + sr * sp * sy;
  float qx = sr * cp * cy - cr * sp * sy;
  float qy = cr * sp * cy + sr * cp * sy;
  float qz = cr * cp * sy - sr * sp * cy;

  quat_x10000[0] = quat_to_x10000(qx);
  quat_x10000[1] = quat_to_x10000(qy);
  quat_x10000[2] = quat_to_x10000(qz);
  quat_x10000[3] = quat_to_x10000(qw);
}

// One-shot init of the onboard IMU: power the sensor rail, then init and
// configure the fusion service. Best-effort: on failure the IMU adv path
// stays idle but CTE/CS continue to work.
static void imu_sensor_init(void)
{
  sl_status_t sc;

  (void)sl_board_enable_sensor(SL_BOARD_SENSOR_IMU);

  sc = sl_imu_init();
  if (sc != SL_STATUS_OK) {
    app_log_warning("[APP] sl_imu_init failed: 0x%04lx" APP_LOG_NL,
                    (unsigned long)sc);
    imu_ready = false;
    return;
  }

  sl_imu_configure((float)IMU_ADV_UPDATE_RATE_HZ);
  imu_ready = true;
  app_log_info("[APP] onboard ICM-40627 IMU ready" APP_LOG_NL);
}

// Pull the latest fused sample (if a new one is ready) into the cached
// accel / gyro / quaternion values. Returns true when fresh data was read.
static bool imu_read_sample(imu_sample_t *sample)
{
  uint8_t status = 0U;
  bool fresh = false;

  if (sample == NULL) {
    return false;
  }

  memset(sample, 0, sizeof(*sample));

  if (imu_ready) {
    status |= IMU_STATUS_IMU_INIT_OK;

    if (sl_imu_is_data_ready()) {
      int16_t avec[3];
      int16_t gvec[3];
      int16_t ovec[3];

      sl_imu_update();
      sl_imu_get_acceleration(avec); // milli-g
      sl_imu_get_gyro(gvec);         // centidegrees / s
      sl_imu_get_orientation(ovec);  // centidegrees (Euler)

      imu_last_accel_mg[0] = avec[0];
      imu_last_accel_mg[1] = avec[1];
      imu_last_accel_mg[2] = avec[2];

      // Service reports gyro in 0.01 dps; the OTA format is whole dps.
      imu_last_gyro_dps[0] = sat_i16(gvec[0] / 100);
      imu_last_gyro_dps[1] = sat_i16(gvec[1] / 100);
      imu_last_gyro_dps[2] = sat_i16(gvec[2] / 100);

      euler_centideg_to_quat(ovec, imu_last_quat_x10000);

      status |= IMU_STATUS_IMU_READ_OK;
      fresh = true;
    }
  }

  sample->accel_x_mg = imu_last_accel_mg[0];
  sample->accel_y_mg = imu_last_accel_mg[1];
  sample->accel_z_mg = imu_last_accel_mg[2];

  sample->gyro_x_dps = imu_last_gyro_dps[0];
  sample->gyro_y_dps = imu_last_gyro_dps[1];
  sample->gyro_z_dps = imu_last_gyro_dps[2];

  sample->quat_x_x10000 = imu_last_quat_x10000[0];
  sample->quat_y_x10000 = imu_last_quat_x10000[1];
  sample->quat_z_x10000 = imu_last_quat_x10000[2];
  sample->quat_w_x10000 = imu_last_quat_x10000[3];

  sample->status = status;
  return fresh;
}

// Rebuild and push the IMU sample. The same 24-byte payload feeds two
// transports:
//   * AoA mode (no connection): the dedicated non-connectable advertising set
//     (Flags(3) + ManufacturerData(28) = 31 bytes, legacy adv budget).
//   * CS/connected mode: a GATT notification over the active connection, since
//     a standalone advertising set is starved to ~2-3 Hz while connected.
//   payload = magic(2), ver(1), seq(1), accel(6), gyro(6), quaternion(8).
static void update_imu_advertising_packet(void)
{
  imu_sample_t sample;
  const bool sample_valid = imu_read_sample(&sample);

  if (!bluetooth_ready || imu_set_handle == 0xFFU) {
    return;
  }

  // Fix 1 (phase-lock): only advance the sequence number and refresh the
  // transports on a genuinely new fused sample. Combined with polling at the
  // fusion rate (app_process_action) this strictly ties seq to real data --
  // exactly one seq per sample, no dup/skip churn from adv-vs-refresh phase
  // slip, and set_data/notify are always "ahead" of the on-air interval.
  if (!sample_valid) {
    return;
  }
  sample.status |= IMU_STATUS_SAMPLE_VALID;
  (void)sample.status; // status not transmitted (payload budget)

  // Build the shared 24-byte IMU payload once (single seq per fused sample).
  uint8_t payload[IMU_PAYLOAD_LEN];
  uint8_t p = 0;
  write_u16_le(&payload[p], IMU_PAYLOAD_MAGIC);
  p += 2U;
  payload[p++] = IMU_PAYLOAD_VERSION;
  payload[p++] = imu_sequence++;
  write_u16_le(&payload[p], (uint16_t)sample.accel_x_mg);
  p += 2U;
  write_u16_le(&payload[p], (uint16_t)sample.accel_y_mg);
  p += 2U;
  write_u16_le(&payload[p], (uint16_t)sample.accel_z_mg);
  p += 2U;
  write_u16_le(&payload[p], (uint16_t)sample.gyro_x_dps);
  p += 2U;
  write_u16_le(&payload[p], (uint16_t)sample.gyro_y_dps);
  p += 2U;
  write_u16_le(&payload[p], (uint16_t)sample.gyro_z_dps);
  p += 2U;
  write_u16_le(&payload[p], (uint16_t)sample.quat_x_x10000);
  p += 2U;
  write_u16_le(&payload[p], (uint16_t)sample.quat_y_x10000);
  p += 2U;
  write_u16_le(&payload[p], (uint16_t)sample.quat_z_x10000);
  p += 2U;
  write_u16_le(&payload[p], (uint16_t)sample.quat_w_x10000);
  p += 2U;
  // p == IMU_PAYLOAD_LEN here.

  // --- AoA transport: refresh the dedicated advertising set's payload. ---
  uint8_t adv_data[31];
  uint8_t offset = 0;
  adv_data[offset++] = 2U;
  adv_data[offset++] = AD_TYPE_FLAGS;
  adv_data[offset++] = AD_FLAG_LE_GENERAL_DISCOVERABLE | AD_FLAG_BR_EDR_NOT_SUPPORTED;
  // Manufacturer specific AD: len = type(1) + company_id(2) + payload(24) = 27.
  adv_data[offset++] = 27U;
  adv_data[offset++] = AD_TYPE_MANUFACTURER_SPECIFIC_DATA;
  write_u16_le(&adv_data[offset], SILABS_COMPANY_ID);
  offset += 2U;
  memcpy(&adv_data[offset], payload, IMU_PAYLOAD_LEN);
  offset += IMU_PAYLOAD_LEN;
  (void)sl_bt_legacy_advertiser_set_data(imu_set_handle, 0, offset, adv_data);

  // --- CS/connected transport: notify the subscribed peer. ---
  // Scheduled connection events sustain the full 10 Hz that the starved
  // advertising set cannot deliver while connected.
  if ((active_connection != 0xFFU) && imu_notify_enabled) {
    (void)sl_bt_gatt_server_send_notification(active_connection,
                                              gattdb_imu_data,
                                              IMU_PAYLOAD_LEN,
                                              payload);
  }
}

// Set the IMU broadcast rate (on-air advertising cadence). The payload refresh
// period is matched to the broadcast period so every packet carries fresh
// fused data without needless SPI reads. Safe to call once the stack is up.
static void imu_set_rate(uint8_t rate_hz)
{
  if (rate_hz == 0U) {
    rate_hz = 1U;
  }
  imu_update_period_ticks = imu_timer_freq_hz / rate_hz;
  if (imu_update_period_ticks == 0U) {
    imu_update_period_ticks = 1U;
  }
  if (!bluetooth_ready || imu_set_handle == 0xFFU) {
    return;
  }
  // Advertising interval in 0.625 ms units: (1000 / rate_hz) ms / 0.625.
  uint32_t interval = 1600U / rate_hz;
  (void)sl_bt_advertiser_stop(imu_set_handle);
  (void)sl_bt_advertiser_set_timing(imu_set_handle, interval, interval, 0, 0);
  (void)sl_bt_legacy_advertiser_start(imu_set_handle,
                                      sl_bt_legacy_advertiser_non_connectable);
}

// BTN0 action: tear down all radio activity and halt the Bluetooth controller
// so the power manager can drop the MCU into EM2 standby. The buttons are in
// interrupt mode, so a later BTN1 press still wakes the device. Restart is a
// full system reboot (BTN1) which re-runs the default boot init.
static void enter_standby(void)
{
  // Drop any open connection so the peer (CS initiator / AoA locator) is freed.
  if (active_connection != 0xFFU) {
    (void)sl_bt_connection_close(active_connection);
    active_connection = 0xFFU;
    imu_notify_enabled = false;
  }
  // Stop the user advertising sets (connectable beacon + IMU broadcaster).
  if (imu_set_handle != 0xFFU) {
    (void)sl_bt_advertiser_stop(imu_set_handle);
  }
  if (advertising_set_handle != 0xFFU) {
    (void)sl_bt_advertiser_stop(advertising_set_handle);
  }
  // Power down the onboard ICM-40627 IMU rail.
  if (imu_ready) {
    (void)sl_board_disable_sensor(SL_BOARD_SENSOR_IMU);
    imu_ready = false;
  }
  // Halt the BLE controller: this forces the radio idle (including the
  // component-owned CTE advertiser) so no further transmissions occur and the
  // device is allowed to sleep in EM2 until a button interrupt wakes it.
  (void)sl_bt_system_halt(1);
  standby = true;
  app_log_info("[APP] BTN0: halted -> low-power standby" APP_LOG_NL);
}

/**************************************************************************//**
 * Application Init.
 *****************************************************************************/
void app_init(void)
{
  imu_timer_freq_hz = sl_sleeptimer_get_timer_frequency();
  if (imu_timer_freq_hz == 0U) {
    imu_timer_freq_hz = 32768U;
  }

  imu_update_period_ticks = imu_timer_freq_hz / IMU_RATE_AOA_HZ;
  if (imu_update_period_ticks == 0U) {
    imu_update_period_ticks = 1U;
  }

  // sl_imu_init() runs a blocking gyro calibration; keep the tag still at
  // power-up. Doing it here (before the BLE boot event) keeps the stack
  // event handler responsive.
  imu_sensor_init();
}

/**************************************************************************//**
 * Application Process Action.
 *****************************************************************************/
void app_process_action(void)
{
  uint32_t now_tick;

  // Service button power-control requests from the super loop (outside the
  // GPIO interrupt context).
  if (resume_requested) {
    resume_requested = false;
    app_log_info("[APP] BTN1: restart from default state" APP_LOG_NL);
    sl_bt_system_reboot();   // reboot -> full default-state re-init; no return
    return;
  }
  if (halt_requested) {
    halt_requested = false;
    enter_standby();
    return;
  }

  if (standby || !bluetooth_ready) {
    return;
  }

  now_tick = sl_sleeptimer_get_tick_count();
  // Fix 1 (phase-lock): poll at the fusion sample rate, not the on-air adv
  // cadence. update_imu_advertising_packet() gates on fresh fused data, so the
  // payload/seq is always refreshed "ahead" of the advertiser interval -- no
  // packet is stale-repeated (dup seq) or overwritten before it airs (skip seq).
  if ((uint32_t)(now_tick - imu_last_update_tick)
        >= (imu_timer_freq_hz / IMU_ADV_UPDATE_RATE_HZ)) {
    imu_last_update_tick = now_tick;
    update_imu_advertising_packet();
  }
}

/**************************************************************************//**
 * Bluetooth stack event handler.
 * This overrides the default weak implementation.
 *
 * @param[in] evt Event coming from the Bluetooth stack.
 *****************************************************************************/
#if CS_TAG_REQUIRE_BOND
// Configure SC-only, bondable, debug-key-rejecting pairing (Layer 1). No
// MITM_REQUIRED: with NoInputNoOutput IO capability and no usable OOB channel
// there is no MITM-capable association method, so requesting it would only make
// pairing fail. Called once from the boot handler when the feature is enabled.
static void tag_security_configure(void)
{
  const uint8_t flags = SL_BT_SM_CONFIGURATION_BONDING_REQUIRED
                      | SL_BT_SM_CONFIGURATION_SC_ONLY
                      | SL_BT_SM_CONFIGURATION_REJECT_DEBUG_KEYS;
  sl_status_t sc = sl_bt_sm_configure(flags,
                                      sl_bt_sm_io_capability_noinputnooutput);
  if (sc != SL_STATUS_OK) {
    app_log_warning("[APP] [SEC] sm_configure -> 0x%04lx" APP_LOG_NL,
                    (unsigned long)sc);
  }
  sc = sl_bt_sm_set_bondable_mode(1);
  if (sc != SL_STATUS_OK) {
    app_log_warning("[APP] [SEC] set_bondable_mode -> 0x%04lx" APP_LOG_NL,
                    (unsigned long)sc);
  }
  app_log_info("[APP] [SEC] SC-only bondable pairing enabled" APP_LOG_NL);
}
#endif // CS_TAG_REQUIRE_BOND

void sl_bt_on_event(sl_bt_msg_t *evt)
{
  sl_status_t sc;

  switch (SL_BT_MSG_ID(evt->header)) {
    // -------------------------------
    // This event indicates the device has started and the radio is ready.
    // Do not call any stack command before receiving this boot event!
    case sl_bt_evt_system_boot_id:
      // Allow the CS reflector to drive its max TX power range.
      {
        int16_t min_tx_power_x10 = CS_REFLECTOR_MIN_TX_POWER_DBM * 10;
        int16_t max_tx_power_x10 = CS_REFLECTOR_MAX_TX_POWER_DBM * 10;
        (void)sl_bt_system_set_tx_power(min_tx_power_x10,
                                        max_tx_power_x10,
                                        &min_tx_power_x10,
                                        &max_tx_power_x10);
      }

      // Apply the wireless/wired CS antenna offset table for brd2606.
      (void)cs_antenna_configure(CS_REFLECTOR_ANTENNA_OFFSET);

#if CS_TAG_REQUIRE_BOND
      // Optional Layer 1 pairing hardening (default off; see top of file).
      tag_security_configure();
#endif

      // Create an advertising set.
      sc = sl_bt_advertiser_create_set(&advertising_set_handle);
      app_assert_status(sc);

      // Generate data for advertising.
      sc = sl_bt_legacy_advertiser_generate_data(advertising_set_handle,
                                                 sl_bt_advertiser_general_discoverable);
      app_assert_status(sc);

      // Set advertising interval to 250 ms. The connectable legacy adv
      // is the CS reflector discovery beacon; once an initiator has bonded
      // it reconnects from cache, so a slower beacon costs only first-time
      // discovery latency and frees radio airtime for the CTE extended-adv
      // set (the AoA bottleneck — see PIPELINE §2.1 / §7.4). original == 100ms
      sc = sl_bt_advertiser_set_timing(
        advertising_set_handle,
        400, // min. adv. interval (milliseconds * 1.6) = 250 ms original == 160
        400, // max. adv. interval (milliseconds * 1.6) = 250 ms original == 160
        0,   // adv. duration
        0);  // max. num. adv. events
      app_assert_status(sc);

      // Enable connections.
      sc = sl_bt_legacy_advertiser_start(advertising_set_handle,
                                         sl_bt_legacy_advertiser_connectable);
      app_assert_status(sc);

      // -------- IMU advertising set: non-connectable, dedicated broadcaster
      // for the onboard IMU manufacturer data. Never preempted by connection
      // events. Best-effort: if the stack cannot allocate a second set we do
      // NOT halt the MCU — CTE/CS already work above and the IMU update path
      // simply skips while imu_set_handle stays 0xFF.
      sc = sl_bt_advertiser_create_set(&imu_set_handle);
      if (sc != SL_STATUS_OK) {
        imu_set_handle = 0xFFU;
        app_log_warning("[APP] IMU adv set alloc failed: 0x%04lx" APP_LOG_NL,
                        (unsigned long)sc);
      } else {
        // Use the device identity address (same as the connectable set) so
        // the locator-side tag id matches across angle/ and imu/ topics.
        (void)sl_bt_advertiser_clear_random_address(imu_set_handle);
        // Boot into AoA mode at IMU_RATE_AOA_HZ (interval 1600/10 = 160 *
        // 0.625 ms = 100 ms => 10 Hz). The Silabs proprietary CTE extended adv
        // (gatt_service_cte_silabs @ 20 ms) is what the AoA locator syncs to;
        // the IMU set shares airtime with it and the host decimates the IMU
        // stream as needed. When a CS initiator connects we keep IMU fast and
        // additionally stream it over the CS GATT link (see connection events).
        (void)sl_bt_advertiser_set_timing(imu_set_handle,
                                          1600U / IMU_RATE_AOA_HZ,
                                          1600U / IMU_RATE_AOA_HZ, 0, 0);
        (void)sl_bt_legacy_advertiser_start(imu_set_handle,
                                            sl_bt_legacy_advertiser_non_connectable);
      }

      bluetooth_ready = true;
      imu_last_update_tick = sl_sleeptimer_get_tick_count();
      update_imu_advertising_packet();

      app_log_info("[APP] AoA tag + CS reflector + IMU POC ready" APP_LOG_NL);
      break;

    // -------------------------------
    // This event indicates that a new connection was opened.
    case sl_bt_evt_connection_opened_id:
      connection_count++;
      // Spin up a reflector instance for every inbound connection. If the
      // peer is the AoA locator (CTE only) the CS handshake will simply
      // never start and the reflector instance stays idle until disconnect.
      {
        uint8_t conn = evt->data.evt_connection_opened.connection;
        // Remember the peer so the IMU cadence loop can notify it. A fresh
        // connection has not yet subscribed to the IMU characteristic.
        active_connection = conn;
        imu_notify_enabled = false;
        sl_status_t rc = cs_reflector_create(conn, &cs_reflector_config);
        if (rc != SL_STATUS_OK) {
          app_log_warning("[APP] cs_reflector_create(%u) -> 0x%04lx" APP_LOG_NL,
                          conn, (unsigned long)rc);
        }
      }
      // Enter CS mode on the first connection: the gated initiator only
      // connects when it wants to range. Pause the CTE tone stream and push
      // the IMU broadcaster to 10 Hz now that CTE has freed the airtime.
      if (connection_count == 1) {
        cte_pause();
        imu_set_rate(IMU_RATE_CS_HZ);
      }
      // Do NOT re-advertise while a peer is connected. The CS initiator's
      // scanner is still running, so any new advertising packet would cause
      // it to open a duplicate connection (CS_INITIATOR_MAX_CONNECTIONS=1
      // → 0x1C / SL_STATUS_NO_MORE_RESOURCE → reconnect storm that starves
      // the primary CS procedure). Single-peer is fine for this POC.
      break;

    // -------------------------------
    // This event indicates that a connection was closed.
    case sl_bt_evt_connection_closed_id:
      {
        uint8_t conn = evt->data.evt_connection_closed.connection;
        if (conn == active_connection) {
          active_connection = 0xFFU;
          imu_notify_enabled = false;
        }
        if (cs_reflector_identify(conn)) {
          (void)cs_reflector_delete(conn);
        }
      }
      connection_count--;
      // Always resume advertising once we're free.
      if (connection_count == 0) {
        sc = sl_bt_legacy_advertiser_start(advertising_set_handle,
                                           sl_bt_legacy_advertiser_connectable);
        app_assert_status(sc);
        // Back to AoA mode: restore the 20 ms CTE tone stream so the locator
        // re-acquires, and return the IMU broadcaster to IMU_RATE_AOA_HZ.
        cte_resume();
        imu_set_rate(IMU_RATE_AOA_HZ);
      }
      break;

    // -------------------------------
    // Peer (un)subscribed to a GATT characteristic. Track the IMU Data CCCD so
    // we only notify when the CS initiator has enabled notifications.
    case sl_bt_evt_gatt_server_characteristic_status_id:
      if (evt->data.evt_gatt_server_characteristic_status.characteristic
          == gattdb_imu_data) {
        uint8_t status_flags =
          evt->data.evt_gatt_server_characteristic_status.status_flags;
        if (status_flags == (uint8_t)sl_bt_gatt_server_client_config) {
          uint16_t cfg =
            evt->data.evt_gatt_server_characteristic_status.client_config_flags;
          imu_notify_enabled =
            ((cfg & (uint16_t)sl_bt_gatt_server_notification) != 0U);
        }
      }
      break;

#if CS_TAG_REQUIRE_BOND
    // -------------------------------
    // Security Manager outcome logging (Layer 1). The host-side IRK pin
    // (Layer 2) is what actually authorises CS for an enrolled tag.
    case sl_bt_evt_sm_bonded_id:
      app_log_info("[APP] [SEC] bonded (conn %u, bonding %u, sec 0x%02x)" APP_LOG_NL,
                   evt->data.evt_sm_bonded.connection,
                   evt->data.evt_sm_bonded.bonding,
                   evt->data.evt_sm_bonded.security_mode);
      break;
    case sl_bt_evt_sm_bonding_failed_id:
      app_log_warning("[APP] [SEC] bonding failed (conn %u, reason 0x%04x)" APP_LOG_NL,
                      evt->data.evt_sm_bonding_failed.connection,
                      evt->data.evt_sm_bonding_failed.reason);
      break;
#endif // CS_TAG_REQUIRE_BOND

    ///////////////////////////////////////////////////////////////////////////
    // Add additional event handlers here as your application requires!      //
    ///////////////////////////////////////////////////////////////////////////

    // -------------------------------
    // Default event handler.
    default:
      break;
  }
}

// ---------------------------------------------------------------------------
// Onboard button control (BRD2606A).
// ---------------------------------------------------------------------------
// BTN0 -> halt the firmware into low-power standby; BTN1 -> restart from the
// default state. Called from the simple_button driver on every edge; we act on
// the press edge only and defer the work to app_process_action via flags.
#if (SL_SIMPLE_BUTTON_COUNT >= 2)
void sl_button_on_change(const sl_button_t *handle)
{
  if (sl_button_get_state(handle) != SL_SIMPLE_BUTTON_PRESSED) {
    return;
  }
  if (handle == SL_SIMPLE_BUTTON_INSTANCE(0)) {
    halt_requested = true;     // BTN0: enter low-power standby
  } else if (handle == SL_SIMPLE_BUTTON_INSTANCE(1)) {
    resume_requested = true;   // BTN1: restart from default state
  }
}
#endif // SL_SIMPLE_BUTTON_COUNT >= 2
