/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_system_id                      24
#define gattdb_imu_data                       27
#define gattdb_cte                            29
#define gattdb_cte_enable                     31
#define gattdb_adv_cte_min_len                33
#define gattdb_adv_cte_min_tx_count           35
#define gattdb_adv_cte_tx_duration            37
#define gattdb_adv_cte_interval               39
#define gattdb_adv_cte_phy                    41
#define gattdb_ras                            42
#define gattdb_ras_features                   44
#define gattdb_ras_real_time_ranging_data     46
#define gattdb_ras_real_time_cccd             47
#define gattdb_ras_on_demand_ranging_data     49
#define gattdb_ras_on_demand_cccd             50
#define gattdb_ras_cp                         52
#define gattdb_ras_cp_cccd                    53
#define gattdb_ras_ranging_data_ready         55
#define gattdb_ras_ranging_data_ready_cccd    56
#define gattdb_ras_ranging_data_overwritten   58
#define gattdb_ras_ranging_data_overwritten_cccd 59

#define gattdb_generic_attribute_len          2
#define gattdb_service_changed_char_len       4
#define gattdb_database_hash_len              16
#define gattdb_client_support_features_len    1
#define gattdb_device_name_len                8
#define gattdb_device_information_len         2
#define gattdb_manufacturer_name_string_len   12
#define gattdb_model_number_string_len        10
#define gattdb_hardware_revision_string_len   5
#define gattdb_firmware_revision_string_len   8
#define gattdb_system_id_len                  8
#define gattdb_imu_data_len                   24
#define gattdb_cte_len                        2
#define gattdb_ras_len                        2


#endif // __GATT_DB_H
